### ISSUE TITLE
[memo] TODO as of January 10

### ISSUE THREAD

**Issue by MasashiFukuzawa** [MasashiFukuzawa/google-calendar-integration-tester#5]
- [ ] implement test codes
  - [ ] puppeteer/
  - [ ] google-apps-scripts/
- [ ] CI with Github Actions
- [ ] use TypeScript in google-apps-scripts
- [ ] add more information to README
